//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationTier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationTier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream datafast {
            get {
                return ResourceManager.GetStream("datafast", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream difarmes_ambato {
            get {
                return ResourceManager.GetStream("difarmes_ambato", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Difarmes_Mañosca {
            get {
                return ResourceManager.GetStream("Difarmes_Mañosca", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Difarmes_Sur {
            get {
                return ResourceManager.GetStream("Difarmes_Sur", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO___Las_Casas {
            get {
                return ResourceManager.GetStream("ECO___Las_Casas", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO___Real_Audiencia {
            get {
                return ResourceManager.GetStream("ECO___Real_Audiencia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO___Vida_Sana {
            get {
                return ResourceManager.GetStream("ECO___Vida_Sana", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO__Atacames_II {
            get {
                return ResourceManager.GetStream("ECO__Atacames_II", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO__El_Salvador {
            get {
                return ResourceManager.GetStream("ECO__El_Salvador", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco__La_Castellano {
            get {
                return ResourceManager.GetStream("Eco__La_Castellano", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO__Parque__Infanti {
            get {
                return ResourceManager.GetStream("ECO__Parque__Infanti", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_12_de_Noviembre {
            get {
                return ResourceManager.GetStream("Eco_12_de_Noviembre", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_29_de_mayo {
            get {
                return ResourceManager.GetStream("eco_29_de_mayo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_3_de_Julio {
            get {
                return ResourceManager.GetStream("Eco_3_de_Julio", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_5_esquinas {
            get {
                return ResourceManager.GetStream("eco_5_esquinas", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_9_de_Octubre {
            get {
                return ResourceManager.GetStream("Eco_9_de_Octubre", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Alejandro {
            get {
                return ResourceManager.GetStream("Eco_Alejandro", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_America {
            get {
                return ResourceManager.GetStream("Eco_America", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_AMERICAS_CUENCA {
            get {
                return ResourceManager.GetStream("ECO_AMERICAS_CUENCA", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Andinatel_Otavalo {
            get {
                return ResourceManager.GetStream("Eco_Andinatel_Otavalo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_atacames {
            get {
                return ResourceManager.GetStream("eco_atacames", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Atahualpa {
            get {
                return ResourceManager.GetStream("Eco_Atahualpa", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Av__Quito {
            get {
                return ResourceManager.GetStream("Eco_Av__Quito", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Biloxi {
            get {
                return ResourceManager.GetStream("Eco_Biloxi", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Bolivar {
            get {
                return ResourceManager.GetStream("Eco_Bolivar", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Calle_Guayaquil {
            get {
                return ResourceManager.GetStream("Eco_Calle_Guayaquil", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_calle_sucre {
            get {
                return ResourceManager.GetStream("eco_calle_sucre", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Carabobo {
            get {
                return ResourceManager.GetStream("Eco_Carabobo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Carapungo {
            get {
                return ResourceManager.GetStream("Eco_Carapungo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_carcelen {
            get {
                return ResourceManager.GetStream("eco_carcelen", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Carcelen_Bajo {
            get {
                return ResourceManager.GetStream("Eco_Carcelen_Bajo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Catedral {
            get {
                return ResourceManager.GetStream("ECO_Catedral", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Central_Cayambe {
            get {
                return ResourceManager.GetStream("Eco_Central_Cayambe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Central_San_Gabriel {
            get {
                return ResourceManager.GetStream("Eco_Central_San_Gabriel", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Cevallos {
            get {
                return ResourceManager.GetStream("Eco_Cevallos", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Clinica_Ibarra {
            get {
                return ResourceManager.GetStream("Eco_Clinica_Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Clínica_Pichincha {
            get {
                return ResourceManager.GetStream("Eco_Clínica_Pichincha", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Coca {
            get {
                return ResourceManager.GetStream("Eco_Coca", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Colón_Esmeraldas {
            get {
                return ResourceManager.GetStream("Eco_Colón_Esmeraldas", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Comité_del_Pueblo {
            get {
                return ResourceManager.GetStream("Eco_Comité_del_Pueblo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_conocoto {
            get {
                return ResourceManager.GetStream("eco_conocoto", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Copacabana {
            get {
                return ResourceManager.GetStream("Eco_Copacabana", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Cotocollao {
            get {
                return ResourceManager.GetStream("Eco_Cotocollao", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Cruz_Roja_Otavalo {
            get {
                return ResourceManager.GetStream("Eco_Cruz_Roja_Otavalo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_El_BataN {
            get {
                return ResourceManager.GetStream("ECO_El_BataN", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_El_Cisne {
            get {
                return ResourceManager.GetStream("Eco_El_Cisne", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_El_Inca {
            get {
                return ResourceManager.GetStream("Eco_El_Inca", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_El_Recreo {
            get {
                return ResourceManager.GetStream("Eco_El_Recreo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_El_Retorno {
            get {
                return ResourceManager.GetStream("Eco_El_Retorno", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Eloy_Alfaro {
            get {
                return ResourceManager.GetStream("Eco_Eloy_Alfaro", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Florida {
            get {
                return ResourceManager.GetStream("Eco_Florida", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Gonzales_Suarez {
            get {
                return ResourceManager.GetStream("Eco_Gonzales_Suarez", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Hosp__Andrade_Marín {
            get {
                return ResourceManager.GetStream("Eco_Hosp__Andrade_Marín", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Hosp__Quinindé {
            get {
                return ResourceManager.GetStream("Eco_Hosp__Quinindé", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Hosp__San_Vicente {
            get {
                return ResourceManager.GetStream("Eco_Hosp__San_Vicente", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Huachichico {
            get {
                return ResourceManager.GetStream("Eco_Huachichico", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Industrial {
            get {
                return ResourceManager.GetStream("Eco_Industrial", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Inglesa_III {
            get {
                return ResourceManager.GetStream("ECO_Inglesa_III", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Jaime_Roldo {
            get {
                return ResourceManager.GetStream("ECO_Jaime_Roldo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Kenia {
            get {
                return ResourceManager.GetStream("Eco_Kenia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Concordia {
            get {
                return ResourceManager.GetStream("Eco_La_Concordia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Concordia_Dos {
            get {
                return ResourceManager.GetStream("Eco_La_Concordia_Dos", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Estación {
            get {
                return ResourceManager.GetStream("Eco_La_Estación", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_la_J {
            get {
                return ResourceManager.GetStream("Eco_la_J", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Magdalena {
            get {
                return ResourceManager.GetStream("Eco_La_Magdalena", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Merced {
            get {
                return ResourceManager.GetStream("Eco_La_Merced", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Mirage {
            get {
                return ResourceManager.GetStream("Eco_La_Mirage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Salud {
            get {
                return ResourceManager.GetStream("Eco_La_Salud", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_La_Union {
            get {
                return ResourceManager.GetStream("Eco_La_Union", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Lago_Agrio {
            get {
                return ResourceManager.GetStream("Eco_Lago_Agrio", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Las_Lomas {
            get {
                return ResourceManager.GetStream("Eco_Las_Lomas", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Libertad {
            get {
                return ResourceManager.GetStream("Eco_Libertad", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_machachi {
            get {
                return ResourceManager.GetStream("eco_machachi", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_maldonado_amb {
            get {
                return ResourceManager.GetStream("eco_maldonado_amb", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Mariano_Acosta {
            get {
                return ResourceManager.GetStream("Eco_Mariano_Acosta", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Mariscal_Sucre {
            get {
                return ResourceManager.GetStream("Eco_Mariscal_Sucre", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Merc__Mod__Ambato {
            get {
                return ResourceManager.GetStream("Eco_Merc__Mod__Ambato", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Merc__Prin__Tulcán {
            get {
                return ResourceManager.GetStream("Eco_Merc__Prin__Tulcán", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Merc__Princ__Ambato {
            get {
                return ResourceManager.GetStream("Eco_Merc__Princ__Ambato", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_México {
            get {
                return ResourceManager.GetStream("Eco_México", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Mi_Farmacia_El_Carmen {
            get {
                return ResourceManager.GetStream("Eco_Mi_Farmacia_El_Carmen", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Michelena {
            get {
                return ResourceManager.GetStream("Eco_Michelena", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Obelisco {
            get {
                return ResourceManager.GetStream("Eco_Obelisco", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Ofelia {
            get {
                return ResourceManager.GetStream("Eco_Ofelia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Olmedo_Ibarra {
            get {
                return ResourceManager.GetStream("Eco_Olmedo_Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Olmedo_Siglo_XXI {
            get {
                return ResourceManager.GetStream("Eco_Olmedo_Siglo_XXI", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_París {
            get {
                return ResourceManager.GetStream("Eco_París", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Parque_Maldonado {
            get {
                return ResourceManager.GetStream("Eco_Parque_Maldonado", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Parque_Sucre {
            get {
                return ResourceManager.GetStream("Eco_Parque_Sucre", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Pasteur {
            get {
                return ResourceManager.GetStream("Eco_Pasteur", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Patronato_Sur {
            get {
                return ResourceManager.GetStream("Eco_Patronato_Sur", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Pedernales {
            get {
                return ResourceManager.GetStream("Eco_Pedernales", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Pelileo {
            get {
                return ResourceManager.GetStream("Eco_Pelileo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Pío_XII {
            get {
                return ResourceManager.GetStream("Eco_Pío_XII", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Principal_Sto__Dom_ {
            get {
                return ResourceManager.GetStream("Eco_Principal_Sto__Dom_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Quinindé_Dos {
            get {
                return ResourceManager.GetStream("Eco_Quinindé_Dos", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Quinindé_Tres {
            get {
                return ResourceManager.GetStream("Eco_Quinindé_Tres", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Quininde_Uno {
            get {
                return ResourceManager.GetStream("Eco_Quininde_Uno", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Restauración {
            get {
                return ResourceManager.GetStream("Eco_Restauración", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_rod_chavez {
            get {
                return ResourceManager.GetStream("eco_rod_chavez", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Sacha {
            get {
                return ResourceManager.GetStream("Eco_Sacha", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Sacha_Dos {
            get {
                return ResourceManager.GetStream("Eco_Sacha_Dos", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_San_Cayetano {
            get {
                return ResourceManager.GetStream("Eco_San_Cayetano", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_San_Francisco {
            get {
                return ResourceManager.GetStream("Eco_San_Francisco", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_San_Gabriel {
            get {
                return ResourceManager.GetStream("Eco_San_Gabriel", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_San_Lorenzo {
            get {
                return ResourceManager.GetStream("ECO_San_Lorenzo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_San_Miguel {
            get {
                return ResourceManager.GetStream("Eco_San_Miguel", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Sánchez_y_Cifuentes {
            get {
                return ResourceManager.GetStream("Eco_Sánchez_y_Cifuentes", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Santa_Clara {
            get {
                return ResourceManager.GetStream("Eco_Santa_Clara", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Santa_Marianita {
            get {
                return ResourceManager.GetStream("ECO_Santa_Marianita", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Santa_Monica {
            get {
                return ResourceManager.GetStream("Eco_Santa_Monica", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Shushufindi {
            get {
                return ResourceManager.GetStream("ECO_Shushufindi", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Siglo_XXI__Ambato {
            get {
                return ResourceManager.GetStream("ECO_Siglo_XXI__Ambato", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Sto__Dom__Calle_Guayaquil {
            get {
                return ResourceManager.GetStream("Eco_Sto__Dom__Calle_Guayaquil", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_su_Farmacia {
            get {
                return ResourceManager.GetStream("Eco_su_Farmacia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Sudamericana {
            get {
                return ResourceManager.GetStream("Eco_Sudamericana", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ECO_Tena {
            get {
                return ResourceManager.GetStream("ECO_Tena", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Tierra_Nueva {
            get {
                return ResourceManager.GetStream("Eco_Tierra_Nueva", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Turubamba {
            get {
                return ResourceManager.GetStream("Eco_Turubamba", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Universal {
            get {
                return ResourceManager.GetStream("Eco_Universal", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Vaca_de_Castro {
            get {
                return ResourceManager.GetStream("Eco_Vaca_de_Castro", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Eco_Veintimilla_Tulcan {
            get {
                return ResourceManager.GetStream("Eco_Veintimilla_Tulcan", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream eco_villaflora {
            get {
                return ResourceManager.GetStream("eco_villaflora", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Amazonas {
            get {
                return ResourceManager.GetStream("Medi_Amazonas", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_av_america {
            get {
                return ResourceManager.GetStream("medi_av_america", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Brasil {
            get {
                return ResourceManager.GetStream("Medi_Brasil", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Calle_Rocafuerte {
            get {
                return ResourceManager.GetStream("Medi_Calle_Rocafuerte", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Central_Tumbaco {
            get {
                return ResourceManager.GetStream("Medi_Central_Tumbaco", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Clínica_Especialidades {
            get {
                return ResourceManager.GetStream("Medi_Clínica_Especialidades", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_Cumbaya {
            get {
                return ResourceManager.GetStream("MEDI_Cumbaya", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_El_Bosque {
            get {
                return ResourceManager.GetStream("Medi_El_Bosque", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_el_ejido {
            get {
                return ResourceManager.GetStream("medi_el_ejido", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_ely_alf {
            get {
                return ResourceManager.GetStream("medi_ely_alf", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_estad_olimpico {
            get {
                return ResourceManager.GetStream("medi_estad_olimpico", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Ficoa {
            get {
                return ResourceManager.GetStream("Medi_Ficoa", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Gonzalez_Suarez {
            get {
                return ResourceManager.GetStream("Medi_Gonzalez_Suarez", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Granados {
            get {
                return ResourceManager.GetStream("Medi_Granados", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Granda_Centeno {
            get {
                return ResourceManager.GetStream("Medi_Granda_Centeno", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Hospital_Andrade_Marín {
            get {
                return ResourceManager.GetStream("Medi_Hospital_Andrade_Marín", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Indoamerica {
            get {
                return ResourceManager.GetStream("Medi_Indoamerica", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Interoceánica {
            get {
                return ResourceManager.GetStream("Medi_Interoceánica", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Italia {
            get {
                return ResourceManager.GetStream("Medi_Italia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_La_Granja {
            get {
                return ResourceManager.GetStream("Medi_La_Granja", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_la_prensa {
            get {
                return ResourceManager.GetStream("medi_la_prensa", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_la_y {
            get {
                return ResourceManager.GetStream("medi_la_y", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_MAGDA_CARAPUNGO {
            get {
                return ResourceManager.GetStream("MEDI_MAGDA_CARAPUNGO", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_MAGDA_EL_EJIDO {
            get {
                return ResourceManager.GetStream("MEDI_MAGDA_EL_EJIDO", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_MAGDA_RIVER_MALL {
            get {
                return ResourceManager.GetStream("MEDI_MAGDA_RIVER_MALL", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_MAGDA_VENEZUELA {
            get {
                return ResourceManager.GetStream("MEDI_MAGDA_VENEZUELA", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Mariana_de_Jesus {
            get {
                return ResourceManager.GetStream("Medi_Mariana_de_Jesus", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Miravalle {
            get {
                return ResourceManager.GetStream("Medi_Miravalle", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Parq__Cent__Cayambe {
            get {
                return ResourceManager.GetStream("Medi_Parq__Cent__Cayambe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Playa_Chica {
            get {
                return ResourceManager.GetStream("Medi_Playa_Chica", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MEDI_PLAZA {
            get {
                return ResourceManager.GetStream("MEDI_PLAZA", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_pomasqui {
            get {
                return ResourceManager.GetStream("medi_pomasqui", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_puce {
            get {
                return ResourceManager.GetStream("medi_puce", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Real_Audiencia {
            get {
                return ResourceManager.GetStream("Medi_Real_Audiencia", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_republica {
            get {
                return ResourceManager.GetStream("medi_republica", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_san_rafael {
            get {
                return ResourceManager.GetStream("medi_san_rafael", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Medi_Santa_Barbara {
            get {
                return ResourceManager.GetStream("Medi_Santa_Barbara", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream medi_shyris {
            get {
                return ResourceManager.GetStream("medi_shyris", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Oficinas_Ibarra {
            get {
                return ResourceManager.GetStream("Oficinas_Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF__La_Dolorosa_Cayambe {
            get {
                return ResourceManager.GetStream("PAF__La_Dolorosa_Cayambe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Calderón {
            get {
                return ResourceManager.GetStream("PAF_Calderón", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Corazón__de_Jesús {
            get {
                return ResourceManager.GetStream("PAF_Corazón__de_Jesús", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Difarime {
            get {
                return ResourceManager.GetStream("PAF_Difarime", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Dolorosa_Ibarra {
            get {
                return ResourceManager.GetStream("PAF_Dolorosa_Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_El_Carmen__Ibarra {
            get {
                return ResourceManager.GetStream("PAF_El_Carmen__Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_La_Dolorosa__Otavalo {
            get {
                return ResourceManager.GetStream("PAF_La_Dolorosa__Otavalo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Paf_La_Merced_Ibarra {
            get {
                return ResourceManager.GetStream("Paf_La_Merced_Ibarra", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Más_Distribuidora {
            get {
                return ResourceManager.GetStream("PAF_Más_Distribuidora", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Nacional___El_Carmen {
            get {
                return ResourceManager.GetStream("PAF_Nacional___El_Carmen", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Paf_Sagrado_Corazón_2 {
            get {
                return ResourceManager.GetStream("Paf_Sagrado_Corazón_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Paf_Sagrado_Corazón_3 {
            get {
                return ResourceManager.GetStream("Paf_Sagrado_Corazón_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PAF_Yaruqui {
            get {
                return ResourceManager.GetStream("PAF_Yaruqui", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Servicio_de_DataFast {
            get {
                return ResourceManager.GetStream("Servicio_de_DataFast", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Servidores_Matriz_UIO {
            get {
                return ResourceManager.GetStream("Servidores_Matriz_UIO", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream signo {
            get {
                return ResourceManager.GetStream("signo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sylvana_1 {
            get {
                return ResourceManager.GetStream("Sylvana_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sylvana_2 {
            get {
                return ResourceManager.GetStream("Sylvana_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sylvana_3 {
            get {
                return ResourceManager.GetStream("Sylvana_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sylvana_4 {
            get {
                return ResourceManager.GetStream("Sylvana_4", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Zerma {
            get {
                return ResourceManager.GetStream("Zerma", resourceCulture);
            }
        }
    }
}
